title: Blog Lerntagebuch Bibliotheks- und Archivinformatik
author: Tanja
description: > # this means to ignore newlines
  Lerntagebuch für den Kurs Bibliotheks- und Archivinformatik FS2023

# social links
github_username:  tanjastad # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
